Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                  count    min threads    max threads
-----------------  -------  -------------  -------------
maf_retrieval_gdc        1              1              1
total                    1              1              1

Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1):
	maf_retrieval_gdc
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1):
	maf_retrieval_gdc
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

[Fri Mar 10 15:31:18 2023]
rule maf_retrieval_gdc:
    jobid: 0
    reason: Rules with neither input nor output files are always executed.
    resources: tmpdir=/var/folders/t_/62401zpn7dj6xlnzf_bjdsb00000gn/T

Full Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 466, in _open
    return open(path_or_uri, mode, encoding=None if "b" in mode else encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/smart_open/smart_open_lib.py", line 177, in open
    fobj = _shortcut_open(
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/smart_open/smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2577, in run_wrapper
    run(
  File "/Users/kay/Programming/Project/Snakefile", line 10, in __rule_maf_retrieval_gdc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/script.py", line 1519, in script
    path, source, language, is_local, cache_path = get_source(
                                                   ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/script.py", line 1442, in get_source
    with sourcecache.open(source_file) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 376, in open
    cache_entry = self._cache(source_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 407, in _cache
    self._do_cache(source_file, cache_entry)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 412, in _do_cache
    with self._open_local_or_remote(source_file, "rb") as source:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 441, in _open_local_or_remote
    return self._open(source_file, mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 468, in _open
    raise WorkflowError("Failed to open source file {}".format(path_or_uri), e)
snakemake.exceptions.WorkflowError: Failed to open source file /Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh'

[Fri Mar 10 15:31:18 2023]
Error in rule maf_retrieval_gdc:
    jobid: 0

Full Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 466, in _open
    return open(path_or_uri, mode, encoding=None if "b" in mode else encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/smart_open/smart_open_lib.py", line 177, in open
    fobj = _shortcut_open(
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/smart_open/smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2577, in run_wrapper
    run(
  File "/Users/kay/Programming/Project/Snakefile", line 10, in __rule_maf_retrieval_gdc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/script.py", line 1519, in script
    path, source, language, is_local, cache_path = get_source(
                                                   ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/script.py", line 1442, in get_source
    with sourcecache.open(source_file) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 376, in open
    cache_entry = self._cache(source_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 407, in _cache
    self._do_cache(source_file, cache_entry)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 412, in _do_cache
    with self._open_local_or_remote(source_file, "rb") as source:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 441, in _open_local_or_remote
    return self._open(source_file, mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/sourcecache.py", line 468, in _open
    raise WorkflowError("Failed to open source file {}".format(path_or_uri), e)
snakemake.exceptions.WorkflowError: Failed to open source file /Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 667, in _callback
    raise ex
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 653, in cached_or_run
    run_func(*args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2613, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: WorkflowError in file /Users/kay/Programming/Project/Snakefile, line 6:
Failed to open source file /Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh'
  File "/Users/kay/Programming/Project/Snakefile", line 6, in __rule_maf_retrieval_gdc

RuleException:
WorkflowError in file /Users/kay/Programming/Project/Snakefile, line 6:
Failed to open source file /Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kay/Programming/Project/scripts/get_maf.pyscripts/unpack_main.shscripts/unpack_sub.sh'
  File "/Users/kay/Programming/Project/Snakefile", line 6, in __rule_maf_retrieval_gdc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-10T153117.804588.snakemake.log
unlocking
removing lock
removing lock
removed all locks
