Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job           count    min threads    max threads
----------  -------  -------------  -------------
unpack_all        1              1              1
total             1              1              1

Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1):
	unpack_all
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1):
	unpack_all
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

[Fri Mar 10 15:53:15 2023]
rule unpack_all:
    jobid: 0
    reason: Rules with neither input nor output files are always executed.
    resources: tmpdir=/var/folders/t_/62401zpn7dj6xlnzf_bjdsb00000gn/T

Full Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2577, in run_wrapper
    run(
  File "/Users/kay/Programming/Project/Snakefile", line 21, in __rule_unpack_all
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/shell.py", line 300, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  scripts/unpack_main.shscripts/unpack_sub.sh' returned non-zero exit status 1.

[Fri Mar 10 15:53:15 2023]
Error in rule unpack_all:
    jobid: 0
    shell:
        scripts/unpack_main.shscripts/unpack_sub.sh
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2577, in run_wrapper
    run(
  File "/Users/kay/Programming/Project/Snakefile", line 21, in __rule_unpack_all
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/shell.py", line 300, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  scripts/unpack_main.shscripts/unpack_sub.sh' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 667, in _callback
    raise ex
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 653, in cached_or_run
    run_func(*args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 2613, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /Users/kay/Programming/Project/Snakefile, line 9:
Command 'set -euo pipefail;  scripts/unpack_main.shscripts/unpack_sub.sh' returned non-zero exit status 1.
  File "/Users/kay/Programming/Project/Snakefile", line 9, in __rule_unpack_all

RuleException:
CalledProcessError in file /Users/kay/Programming/Project/Snakefile, line 9:
Command 'set -euo pipefail;  scripts/unpack_main.shscripts/unpack_sub.sh' returned non-zero exit status 1.
  File "/Users/kay/Programming/Project/Snakefile", line 9, in __rule_unpack_all
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-03-10T155315.670193.snakemake.log
unlocking
removing lock
removing lock
removed all locks
